---
galaxy_info:
  role_name: "phpenv"
  author: "Vincent Fricou"
  namespace: "vfricou"
  description: 'Deploy phpenv on remote target'
  license: BSD-3
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: CentOS
      versions:
        - 7
    - name: Rocky
      versions:
        - 8

dependencies: []
